### ISSUE TITLE
Please add the dll version for Windows

### ISSUE THREAD

**Issue by OSPanel** [php/pecl-encryption-mcrypt#14] opened 2023-03-15 18:56 UTC
Please add the latest version of libraries for Windows (TS version) for all supported PHP versions.
Currently, version 1.0.4 is the latest available for download in the PECL repository.

**Comment by OzanKurt** [comment] 2023-08-25 14:03
Bump

**Comment by derickr** [comment] 2023-10-10 09:27
Duplicate of #16, so closing. (Also, adding 'Bump' is unlikely to get a faster response and is considered rude).

**Closed as completed by derickr** 2023-10-10 09:27 UTC
