### ISSUE TITLE
PHP 8.2 MCrypt not instaling

### ISSUE THREAD

**Issue by psinghracknap** [php/pecl-encryption-mcrypt#16] opened 2023-07-12 06:18 UTC
How can we install the mcrypt 1.0.6 in php 8.2 windows xampp, as there is no DLL file is there.

**Comment by OzanKurt** [comment] 2023-08-25 14:03
bump

**Comment by derickr** [comment] 2023-10-10 09:34
Duplicate of #12 — a DLL for PHP 8.2 will not be made available.

**Closed as completed by derickr** 2023-10-10 09:34 UTC
